name: ci

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repo
        uses: actions/checkout@v2
      - name: Set up Python
        uses: actions/setup-python@v2
      - name: Run pre-commit
        uses: pre-commit/action@v2.0.3

  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        # VTK is still missing for 3.10
        python-version: ["3.7", "3.8", "3.9"]
    steps:
      - uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}

      # Don't use lfs directly, but cache the lfs results.
      # See <https://github.com/actions/checkout/issues/165#issuecomment-657673315>.
      - name: Checkout code
        uses: actions/checkout@v2
        # with:
        #   lfs: true
      - name: Create LFS file list
        run: git lfs ls-files -l | cut -d' ' -f1 | sort > .lfs-assets-id
      - name: Restore LFS cache
        uses: actions/cache@v2
        id: lfs-cache
        with:
          path: .git/lfs
          key: lfs-${{ hashFiles('.lfs-assets-id') }}-v1
      - name: Git LFS Pull
        run: git lfs pull

      - name: Install system dependencies
        run: sudo apt-get install gmsh
      - name: Test with tox
        run: |
          pip install tox
          tox -- --cov colorio --cov-report xml --cov-report term
      - uses: codecov/codecov-action@v1
        if: ${{ matrix.python-version == '3.9' }}
